## Lewis Core Permiability Consolidation

### Data Importation

In [1]:
import pandas as pd

df = pd.read_csv('ALL_por_perm_data_CSV.csv')
df

,filename,API,well_name,formation,depth_new,K inf md,Kair md,perm_md,por_percnt,perm_horz_md,Perm Ka Max md,perm_klink_md,grain_density,Comment,Unnamed: 14
0,C720477A.pdf,049-007-20477,1 Champlin 276 AMOCO D,LEWIS,8574.5,NaN,NaN,NaN,12.0,0.604,NaN,NaN,2.67,NaN,NaN
1,C720477A.pdf,049-007-20477,1 Champlin 276 AMOCO D,LEWIS,8575.5,NaN,NaN,NaN,10.2,0.097,NaN,NaN,2.67,NaN,NaN
2,C720477A.pdf,049-007-20477,1 Champlin 276 AMOCO D,LEWIS,8576.5,NaN,NaN,NaN,13.1,4.13,NaN,NaN,2.66,NaN,NaN
3,C720477A.pdf,049-007-20477,1 Champlin 276 AMOCO D,LEWIS,8577.5,NaN,NaN,NaN,10.7,0.501,NaN,NaN,2.66,NaN,NaN
4,C720477A.pdf,049-007-20477,1 Champlin 276 AMOCO D,LEWIS,8578.5,NaN,NaN,NaN,4.6,0.157,NaN,NaN,2.67,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1540,921052A.pdf,049-009-21052,1-26 Federal,LEWIS,6399.0,NaN,NaN,0.25,16.5,NaN,NaN,NaN,NaN,NaN,NaN
1541,921052A.pdf,049-009-21052,1-26 Federal,LEWIS,6402.0,NaN,NaN,0.05,14.8,NaN,NaN,NaN,NaN,NaN,NaN
1542,921052A.pdf,049-009-21052,1-26 Federal,LEWIS,6404.0,NaN,NaN,0.08,14.8,NaN,NaN,NaN,NaN,NaN,NaN
1543,921052A.pdf,049-009-21052,1-26 Federal,LEWIS,6406.0,NaN,NaN,0.75,16.4,NaN,NaN,NaN,NaN,NaN,NaN
1544,921052A.pdf,049-009-21052,1-26 Federal,LEWIS,6408.0,NaN,NaN,0.35,15.5,NaN,NaN,NaN,NaN,NaN,NaN

### Defining Column Order of Ranked Importance

In [2]:
col_order = ['K inf md',
           'Kair md', 
           'perm_md', 
           'perm_horz_md', 
           'Perm Ka Max md', 
           'perm_klink_md']

### Subsetting Dataframe

In [3]:
df2 = df[col_order]
df2

      K inf md  Kair md  perm_md perm_horz_md Perm Ka Max md  perm_klink_md
0          NaN      NaN      NaN        0.604            NaN            NaN
1          NaN      NaN      NaN        0.097            NaN            NaN
2          NaN      NaN      NaN         4.13            NaN            NaN
3          NaN      NaN      NaN        0.501            NaN            NaN
4          NaN      NaN      NaN        0.157            NaN            NaN
...        ...      ...      ...          ...            ...            ...
1540       NaN      NaN     0.25          NaN            NaN            NaN
1541       NaN      NaN     0.05          NaN            NaN            NaN
1542       NaN      NaN     0.08          NaN            NaN            NaN
1543       NaN      NaN     0.75          NaN            NaN            NaN
1544       NaN      NaN     0.35          NaN            NaN            NaN

[1545 rows x 6 columns]

### Changing All Columns to Numeric

In [4]:
df2['K inf md'] = pd.to_numeric(df2['K inf md'],errors='coerce')
df2['Kair md'] = pd.to_numeric(df2['Kair md'],errors='coerce')
df2['perm_md'] = pd.to_numeric(df2['perm_md'],errors='coerce')
df2['perm_horz_md'] = pd.to_numeric(df2['perm_horz_md'],errors='coerce')
df2['Perm Ka Max md'] = pd.to_numeric(df2['Perm Ka Max md'],errors='coerce')
df2['perm_klink_md'] = pd.to_numeric(df2['perm_klink_md'],errors='coerce')

<ipython-input-4-550461c54609>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['K inf md'] = pd.to_numeric(df2['K inf md'],errors='coerce')
<ipython-input-4-550461c54609>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Kair md'] = pd.to_numeric(df2['Kair md'],errors='coerce')
<ipython-input-4-550461c54609>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['perm_md'] = pd.to_numeric(df2['perm_md'],errors='coerce')
<ipython-input-4-550461c54609>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['perm_horz_md'] = pd.to_numeric(df2['perm_horz_md'],errors='coerce')
<ipython-input-4-550461c54609>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Perm Ka Max md'] = pd.to_numeric(df2['Perm Ka Max md'],errors='coerce')
<ipython-input-4-550461c54609>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['perm_klink_md'] = pd.to_numeric(df2['perm_klink_md'],errors='coerce')

### Creating Function to Pull Permeabilities from Dataframe in Ranked Order

In [5]:
def singleval(row):
    if row['K inf md'] > 0:
        val = row['K inf md']
    elif row['Kair md'] > 0:
        val = row['Kair md']
    elif row['perm_md'] > 0:
        val = row['perm_md']
    elif row['perm_horz_md'] > 0:
        val = row['perm_horz_md']
    elif row['Perm Ka Max md'] > 0:
        val = row['Perm Ka Max md']
    else:
        row['perm_klink_md'] > 0
        val = row['perm_klink_md']
    return val

df2['final_perm'] = df2.apply(singleval, axis=1)

<ipython-input-5-63799ad5c880>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['final_perm'] = df2.apply(singleval, axis=1)

### Dataframe Showing Final Permiability for Each Sample

In [6]:
df2

,K inf md,Kair md,perm_md,perm_horz_md,Perm Ka Max md,perm_klink_md,final_perm
0,NaN,NaN,NaN,0.604,NaN,NaN,0.604
1,NaN,NaN,NaN,0.097,NaN,NaN,0.097
2,NaN,NaN,NaN,4.130,NaN,NaN,4.130
3,NaN,NaN,NaN,0.501,NaN,NaN,0.501
4,NaN,NaN,NaN,0.157,NaN,NaN,0.157
...,...,...,...,...,...,...,...
1540,NaN,NaN,0.25,NaN,NaN,NaN,0.250
1541,NaN,NaN,0.05,NaN,NaN,NaN,0.050
1542,NaN,NaN,0.08,NaN,NaN,NaN,0.080
1543,NaN,NaN,0.75,NaN,NaN,NaN,0.750
1544,NaN,NaN,0.35,NaN,NaN,NaN,0.350